CREATE TABLE IF NOT EXISTS `#__azurapagebuilder_pages` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `alias` varchar(255) NOT NULL,
  `shortcode` text NOT NULL,
  `elementsArray` text NOT NULL,
  `introtext` text NOT NULL,
  `fulltext` text NOT NULL,
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(11) NOT NULL DEFAULT '0',
  `created_by_alias` varchar(250) NOT NULL,
  `checked_out` int(11) NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `hits` int(11) NOT NULL DEFAULT '0',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int(11) NOT NULL DEFAULT '0',
  `access` int(10) NOT NULL DEFAULT '1',
  `language` varchar(25) NOT NULL,
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ordering` int(11) NOT NULL,
  `params` text NOT NULL,
  `alt_layout` varchar(250) NOT NULL,
  `customCssLinks` text NOT NULL,
  `customJsLinks` text NOT NULL,
  `customJsButtonLinks` text NOT NULL,
  `customJsBottomScript` text NOT NULL,
  `jQueryLinkType` text NOT NULL,
  `noConflict` text NOT NULL,
  `metadata` text NOT NULL,
  `metadesc` text NOT NULL,
  `metakey` text NOT NULL,
  `tags` text NOT NULL,
  `version` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `#__azurapagebuilder_elements` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `pageID` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `type` varchar(250) DEFAULT NULL,
  `hasChild` tinyint(4) NOT NULL DEFAULT '0',
  `level` int(11) NOT NULL DEFAULT '0',
  `hasChildID` int(11) DEFAULT NULL,
  `hasParentID` int(11) DEFAULT NULL,
  `shortcode` text NOT NULL,
  `object` text,
  `content` text NOT NULL,
  `attrs` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `elementOrder` int(11) NOT NULL,
  `published` tinyint(4) NOT NULL DEFAULT '1',
  `trash` tinyint(4) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(11) NOT NULL,
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int(11) NOT NULL,
  `language` varchar(50) NOT NULL DEFAULT '*',
  PRIMARY KEY (`id`),
  KEY `idx_pageID` (`pageID`),
  KEY `idx_elementOrder` (`elementOrder`),
  KEY `idx_level` (`level`),
  KEY `idx_hasChildID` (`hasChildID`),
  KEY `idx_hasParentID` (`hasParentID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;