<?php

define('HOSTNAME',"localhost");
define('DBNAME',"malariafpmch_db");
define('DBUSER',"root");
define('DBPWD', "");
define('SITETITLEENG', "Health Commodity Dashboard");
define('SITETITLEFRN', "Health Commodity Dashboard1");
define('JBASEURL', "http://localhost/ospsante/administrator/components/com_jcode/source/");

define('SITEROOT','/ospsante/');
define('SITEDOCUMENT',$_SERVER['DOCUMENT_ROOT'].SITEROOT);

define('JOOMLA_DBNAME', "malariafpmch_db");

?>