<?php

define('HOSTNAME',"localhost");
define('DBNAME',"lptt_db");
define('DBUSER',"root");
define('DBPWD', "");
define('SITETITLEENG', "Lab Process Time Tracker");
define('SITETITLEFRN', "Lab Process Time Tracker");

define('JBASEURL', "http://localhost/~lptt/administrator/components/com_jcode/source/");

define('SITEROOT','/');
define('SITEDOCUMENT',$_SERVER['DOCUMENT_ROOT'].SITEROOT);

define('JOOMLA_DBNAME', "lptt_db");

?>